import java.util.Scanner;

public class ForgetfulMachine{
  public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in);
    System.out.println("Please enter your password");
    keyboard.next();

    System.out.println("please enter your passcode");
    keyboard.nextInt();

    System.out.println("for security what is, 1.0 + 1.0");
    keyboard.nextDouble();

    System.out.println("Please enter your password again");
    keyboard.next();

    //Myforgetful

    int age;
    string name,secondName;


  }
}
